In [1]:
import pandas as pd
# matplotlib = this is data visualisation library
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('GL_sal_data_cleaned.csv')
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,...,Revenue,min_salary,max_salary,average-salary,currency,company_txt,age,python_yn,data,analysis
0,Data Scientist,"₹417K-₹1,000K (Glassdoor Est.)",If you are a data junkie who would like to wra...,3.1,BlueJeans\r\n3.1,Bangalore,201 to 500 Employees,2009,Company - Private,Enterprise Software & Network Solutions,...,Unknown / Non-Applicable,417,1000,708.5,LAKh,BlueJeans,11,0,0,0
1,Data Scientist,₹698K-₹960K (Glassdoor Est.),Relocation Assistance Offered Within Country\r...,4.2,Colgate-Palmolive\r\n4.2,Mumbai,10000+ Employees,1806,Company - Public,Consumer Products Manufacturing,...,$10+ billion (USD),698,960,829.0,LAKh,Colgate-Palmolive,214,1,0,1
2,Data Scientist - Technology Development,₹350K-₹679K (Glassdoor Est.),Relocation Level: Domestic\r\n\r\nHiring Manag...,3.6,Micron Technology\r\n3.6,Hyderābād,10000+ Employees,1978,Company - Public,Computer Hardware & Software,...,$10+ billion (USD),350,679,514.5,LAKh,Micron Technology,42,1,0,1
3,Senior / Data Science Engineer,"₹490K-₹1,094K (Glassdoor Est.)","Gainsight™ is a venture-backed, fast-growing t...",4.2,Gainsight\r\n4.2,Hyderābād,501 to 1000 Employees,2009,Company - Private,Enterprise Software & Network Solutions,...,Unknown / Non-Applicable,490,1094,792.0,LAKh,Gainsight,11,1,0,1
4,Business Analyst - Data Science,₹479K-₹700K (Glassdoor Est.),"With a startup spirit and 90,000+ curious and ...",3.8,Genpact\r\n3.8,Bangalore,10000+ Employees,1997,Company - Public,IT Services,...,$2 to $5 billion (USD),479,700,589.5,LAKh,Genpact,23,1,0,1

In [ ]:
df.columns